# Generated by Django 4.1.3 on 2022-12-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('language', models.TextField(max_length=50)),
                ('file_name', models.TextField(max_length=1000)),
            ],
        ),
    ]
